org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=26.1.2
fabric_loader_version=0.19.3
fabric_api_version=0.152.1+26.1.2
loom_version=1.17.14
yacl_version=A6V2zTVY
modmenu_version=18.0.0

mod_version=2.2.1+26.1.2
maven_group=com.minenash
archives_base_name=seamless-loading-screen-rethinking
