org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=26.2
fabric_loader_version=0.19.3
fabric_api_version=0.155.2+26.2
loom_version=1.17.14
yacl_version=cnfPzuFU
modmenu_version=njXb639R

mod_version=1.0.2+26.2
maven_group=com.minenash
archives_base_name=seamless-loading-screen-rethinking
