plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.147'
}

version = project.mod_version
group = project.mod_group_id

base {
    archivesName = project.archives_base_name
}

sourceSets {
    main.java.srcDir '../../shared/src/main/java'
    test.java.srcDir '../../shared/src/test/java'
}

repositories {
    mavenCentral()
    maven { url = 'https://api.modrinth.com/maven' }
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

neoForge {
    version = project.neo_version

    runs {
        client {
            client()
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    implementation "maven.modrinth:1eAoo2KR:${project.yacl_version}"

    testImplementation platform('org.junit:junit-bom:5.11.4')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'com.mojang:logging:1.7.12'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 25
    options.compilerArgs += ['-Xlint:all', '-Xlint:-processing', '-Xlint:-classfile']
}

tasks.named('test', Test) {
    useJUnitPlatform()
}

java {
    withSourcesJar()
}

tasks.withType(Jar).configureEach {
    includeEmptyDirs = false
}
