org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=26.3
fabric_loader_version=0.19.5
fabric_api_version=0.161.0+26.3
loom_version=1.17.21
yacl_version=s9SjoFu1
modmenu_version=21.0.0-beta.1

mod_version=1.0.3+26.3-fabric
maven_group=com.minenash
archives_base_name=seamless-loading-screen-rethinking
