org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

minecraft_version=26.3
neo_version=26.3.0.13-beta
yacl_version=GL24RgOP

mod_id=seamless_loading_screen
mod_version=1.0.3+26.3-neoforge
mod_group_id=com.minenash
archives_base_name=seamless-loading-screen-rethinking
