plugins {
    id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
}

def modVersion = project.mod_version
version = modVersion
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

sourceSets {
    main.java.srcDir '../../shared/src/main/java'
    test.java.srcDir '../../shared/src/test/java'
}

repositories {
    mavenCentral()
    maven { url = 'https://maven.isxander.dev/releases' }
    maven { url = 'https://maven.terraformersmc.com/releases/' }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
    modImplementation "dev.isxander:yet-another-config-lib:${project.yacl_version}-fabric"
    modImplementation "com.terraformersmc:modmenu:${project.modmenu_version}"

    testImplementation platform('org.junit:junit-bom:5.11.4')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

processResources {
    inputs.property 'version', modVersion
    from('LICENSE')
    filesMatching('fabric.mod.json') {
        expand 'version': modVersion
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 21
    options.compilerArgs += ['-Xlint:all', '-Xlint:-processing', '-Xlint:-classfile']
}

tasks.named('test', Test) {
    useJUnitPlatform()
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

tasks.withType(Jar).configureEach {
    includeEmptyDirs = false
}

tasks.named('sourcesJar', Jar) {
    from('LICENSE')
}
