license="MIT"

[[mods]]
modId="seamless_loading_screen_rethinking"
version="1.0.3+26.1.2-neoforge"
displayName="Seamless Loading Screen Rethinking"
iconFile="icon.png"
authors="Minenash, Toffiks"
description='''
Replaces Minecraft's world loading background with the last frame captured when leaving that world.
'''

[[mixins]]
config="seamless_loading_screen-common.mixins.json"

[[dependencies.seamless_loading_screen_rethinking]]
modId="neoforge"
type="required"
versionRange="[26.1.2.109,)"
ordering="NONE"
side="CLIENT"

[[dependencies.seamless_loading_screen_rethinking]]
modId="minecraft"
type="required"
versionRange="[26.1.2]"
ordering="NONE"
side="CLIENT"

[[dependencies.seamless_loading_screen_rethinking]]
modId="yet_another_config_lib_v3"
type="required"
versionRange="[3.9.5,)"
ordering="AFTER"
side="CLIENT"
